name: Build and Deploy (safe secret replacement)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Replace placeholder safely with Python
        run: |
          python3 - << 'EOF'
          import os
          import base64

          secret = os.environ["MY_SECRET"]

          # Read index.html
          with open("index.html", "r", encoding="utf-8") as f:
              html = f.read()

          # Replace placeholder
          html = html.replace("_MY_SECRET_", secret)

          # Write back file
          with open("index.html", "w", encoding="utf-8") as f:
              f.write(html)

          print("✅ Secret injected safely into index.html")
          EOF
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./   # Change to ./build or ./public if you have a build step
